<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoreLibrary\CoreLibrary.csproj" />
    <ProjectReference Include="..\domain\Domain.csproj" />
    <ProjectReference Include="..\infrastructure\infrastructure\infrastructure.csproj" />
  </ItemGroup>

</Project>
